baseURL: https://grubernet.es/
languageCode: en-us
title: grubernet.es
theme: hyde
enableEmoji: true
googleAnalytics: UA-131799127-1

params:
  description: rantings on automation, containers and security
  # themeColor: theme-base-0d
  copyright: ' '
menu:
  links:
    - identifier: github
      name: github.com/darrengruber
      url: https://github.com/darrengruber
    - identifier: dockerhub
      name: hub.docker.com/u/darren
      url: https://hub.docker.com/u/darren
